// Sketch 001 "Instrumento" workbench color theme, in VS Code color-theme format.
// Applied across Theia/Monaco tokens by MonacoThemingService.registerParsedTheme.
// Source of truth for the palette: ai-native-ide/.planning/sketches/001-ide-atmosphere/index.html

export const instrumentColorTheme = {
  "name": "Instrument · 001",
  "type": "dark",
  "colors": {
    "foreground": "#e9eaec",
    "descriptionForeground": "#9b9da4",
    "disabledForeground": "#85888f",
    "errorForeground": "#e3655b",
    "focusBorder": "#79a3d0",
    "widget.border": "#ffffff24",
    "widget.shadow": "#00000066",
    "selection.background": "#ffffff28",
    "icon.foreground": "#9b9da4",
    "sash.hoverBorder": "#79a3d0",

    "window.activeBorder": "#00000000",
    "window.inactiveBorder": "#00000000",

    "textLink.foreground": "#79a3d0",
    "textLink.activeForeground": "#a9c6e6",
    "textPreformat.foreground": "#d9a03c",
    "textBlockQuote.background": "#151619",
    "textBlockQuote.border": "#24262b",
    "textCodeBlock.background": "#1b1c20",

    "editor.background": "#101113",
    "editor.foreground": "#e9eaec",
    "editorCursor.foreground": "#e9eaec",
    "editor.lineHighlightBackground": "#ffffff08",
    "editor.lineHighlightBorder": "#00000000",
    "editor.selectionBackground": "#ffffff28",
    "editor.inactiveSelectionBackground": "#ffffff14",
    "editor.selectionHighlightBackground": "#79a3d033",
    "editor.wordHighlightBackground": "#ffffff12",
    "editor.findMatchBackground": "#d9a03c66",
    "editor.findMatchHighlightBackground": "#d9a03c33",
    "editorWhitespace.foreground": "#ffffff14",
    "editorIndentGuide.background1": "#ffffff10",
    "editorIndentGuide.activeBackground1": "#ffffff24",
    "editorLineNumber.foreground": "#5f6268",
    "editorLineNumber.activeForeground": "#e9eaec",
    "editorRuler.foreground": "#ffffff10",
    "editorBracketMatch.background": "#79a3d022",
    "editorBracketMatch.border": "#79a3d066",
    "editorGutter.background": "#101113",
    "editorGutter.modifiedBackground": "#79a3d0",
    "editorGutter.addedBackground": "#58b287",
    "editorGutter.deletedBackground": "#e3655b",
    "editorError.foreground": "#e3655b",
    "editorWarning.foreground": "#d9a03c",
    "editorInfo.foreground": "#79a3d0",
    "editorHint.foreground": "#58b287",
    "editorOverviewRuler.border": "#00000000",

    "editorWidget.background": "#151619",
    "editorWidget.foreground": "#e9eaec",
    "editorWidget.border": "#ffffff24",
    "editorHoverWidget.background": "#1b1c20",
    "editorHoverWidget.border": "#ffffff24",
    "editorSuggestWidget.background": "#151619",
    "editorSuggestWidget.border": "#ffffff24",
    "editorSuggestWidget.foreground": "#e9eaec",
    "editorSuggestWidget.selectedBackground": "#24262b",
    "editorSuggestWidget.highlightForeground": "#79a3d0",

    "editorGroup.border": "#ffffff12",
    "editorGroupHeader.tabsBackground": "#151619",
    "editorGroupHeader.tabsBorder": "#ffffff12",
    "editorGroupHeader.noTabsBackground": "#101113",
    "editorGroupHeader.border": "#ffffff12",

    "tab.activeBackground": "#101113",
    "tab.activeForeground": "#e9eaec",
    "tab.inactiveBackground": "#151619",
    "tab.inactiveForeground": "#85888f",
    "tab.unfocusedActiveForeground": "#9b9da4",
    "tab.unfocusedInactiveForeground": "#6a6d73",
    "tab.border": "#ffffff12",
    "tab.activeBorder": "#00000000",
    "tab.activeBorderTop": "#e9eaec",
    "tab.hoverBackground": "#1b1c20",
    "tab.hoverForeground": "#e9eaec",
    "tab.activeModifiedBorder": "#79a3d0",
    "tab.inactiveModifiedBorder": "#5f6268",

    "activityBar.background": "#151619",
    "activityBar.foreground": "#e9eaec",
    "activityBar.inactiveForeground": "#85888f",
    "activityBar.border": "#ffffff12",
    "activityBar.activeBorder": "#e9eaec",
    "activityBar.activeBackground": "#24262b",
    "activityBarBadge.background": "#79a3d0",
    "activityBarBadge.foreground": "#0f1620",

    "sideBar.background": "#151619",
    "sideBar.foreground": "#c7c9cd",
    "sideBar.border": "#ffffff12",
    "sideBarTitle.foreground": "#9b9da4",
    "sideBarSectionHeader.background": "#151619",
    "sideBarSectionHeader.foreground": "#85888f",
    "sideBarSectionHeader.border": "#ffffff0d",

    "list.hoverBackground": "#1b1c20",
    "list.hoverForeground": "#e9eaec",
    "list.activeSelectionBackground": "#24262b",
    "list.activeSelectionForeground": "#e9eaec",
    "list.inactiveSelectionBackground": "#1b1c20",
    "list.inactiveSelectionForeground": "#e9eaec",
    "list.focusBackground": "#24262b",
    "list.focusForeground": "#e9eaec",
    "list.highlightForeground": "#79a3d0",
    "list.errorForeground": "#e3655b",
    "list.warningForeground": "#d9a03c",
    "list.emptyBackground": "#151619",
    "tree.indentGuidesStroke": "#ffffff14",

    "statusBar.background": "#151619",
    "statusBar.foreground": "#9b9da4",
    "statusBar.border": "#ffffff12",
    "statusBar.noFolderBackground": "#151619",
    "statusBar.noFolderForeground": "#9b9da4",
    "statusBar.debuggingBackground": "#d9a03c",
    "statusBar.debuggingForeground": "#101113",
    "statusBarItem.hoverBackground": "#24262b",
    "statusBarItem.activeBackground": "#2e3138",
    "statusBarItem.prominentBackground": "#24262b",
    "statusBarItem.prominentHoverBackground": "#2e3138",
    "statusBarItem.remoteBackground": "#24262b",
    "statusBarItem.remoteForeground": "#e9eaec",
    "statusBarItem.errorBackground": "#e3655b",
    "statusBarItem.errorForeground": "#101113",
    "statusBarItem.warningBackground": "#d9a03c",
    "statusBarItem.warningForeground": "#101113",

    "titleBar.activeBackground": "#151619",
    "titleBar.activeForeground": "#e9eaec",
    "titleBar.inactiveBackground": "#151619",
    "titleBar.inactiveForeground": "#85888f",
    "titleBar.border": "#ffffff12",

    "menubar.selectionBackground": "#24262b",
    "menubar.selectionForeground": "#e9eaec",
    "menu.background": "#151619",
    "menu.foreground": "#c7c9cd",
    "menu.border": "#ffffff24",
    "menu.selectionBackground": "#24262b",
    "menu.selectionForeground": "#e9eaec",
    "menu.separatorBackground": "#ffffff14",

    "panel.background": "#151619",
    "panel.border": "#ffffff12",
    "panelTitle.activeForeground": "#e9eaec",
    "panelTitle.inactiveForeground": "#85888f",
    "panelTitle.activeBorder": "#e9eaec",
    "panelInput.border": "#ffffff24",

    "input.background": "#1b1c20",
    "input.foreground": "#e9eaec",
    "input.border": "#ffffff24",
    "input.placeholderForeground": "#85888f",
    "inputOption.activeBorder": "#79a3d0",
    "inputOption.activeBackground": "#79a3d033",
    "inputOption.activeForeground": "#e9eaec",
    "inputValidation.errorBackground": "#3a1f1d",
    "inputValidation.errorBorder": "#e3655b",
    "inputValidation.warningBackground": "#3a301a",
    "inputValidation.warningBorder": "#d9a03c",
    "inputValidation.infoBackground": "#1c2a38",
    "inputValidation.infoBorder": "#79a3d0",

    "dropdown.background": "#1b1c20",
    "dropdown.foreground": "#e9eaec",
    "dropdown.border": "#ffffff24",
    "dropdown.listBackground": "#151619",

    "button.background": "#e9eaec",
    "button.foreground": "#101113",
    "button.hoverBackground": "#ffffff",
    "button.secondaryBackground": "#24262b",
    "button.secondaryForeground": "#e9eaec",
    "button.secondaryHoverBackground": "#2e3138",
    "secondaryButton.foreground": "#e9eaec",
    "secondaryButton.background": "#24262b",
    "secondaryButton.hoverBackground": "#2e3138",

    "badge.background": "#79a3d0",
    "badge.foreground": "#0f1620",

    "checkbox.background": "#1b1c20",
    "checkbox.foreground": "#e9eaec",
    "checkbox.border": "#ffffff24",

    "progressBar.background": "#79a3d0",

    "scrollbar.shadow": "#00000000",
    "scrollbarSlider.background": "#24262b99",
    "scrollbarSlider.hoverBackground": "#2e3138cc",
    "scrollbarSlider.activeBackground": "#2e3138",

    "editorGutter.commentRangeForeground": "#5f6268",
    "peekView.border": "#79a3d0",
    "peekViewEditor.background": "#151619",
    "peekViewResult.background": "#101113",
    "peekViewTitle.background": "#151619",

    "notifications.background": "#151619",
    "notifications.foreground": "#e9eaec",
    "notifications.border": "#ffffff24",
    "notificationCenterHeader.background": "#1b1c20",
    "notificationCenterHeader.foreground": "#9b9da4",
    "notificationsErrorIcon.foreground": "#e3655b",
    "notificationsWarningIcon.foreground": "#d9a03c",
    "notificationsInfoIcon.foreground": "#79a3d0",

    "quickInput.background": "#151619",
    "quickInput.foreground": "#e9eaec",
    "quickInputList.focusBackground": "#24262b",
    "quickInputList.focusForeground": "#e9eaec",
    "pickerGroup.foreground": "#85888f",
    "pickerGroup.border": "#ffffff12",
    "keybindingLabel.background": "#24262b",
    "keybindingLabel.foreground": "#c7c9cd",
    "keybindingLabel.border": "#ffffff14",
    "keybindingLabel.bottomBorder": "#00000033",

    "breadcrumb.foreground": "#85888f",
    "breadcrumb.focusForeground": "#e9eaec",
    "breadcrumb.activeSelectionForeground": "#e9eaec",
    "breadcrumbPicker.background": "#151619",

    "terminal.background": "#101113",
    "terminal.foreground": "#c7c9cd",
    "terminalCursor.foreground": "#e9eaec",
    "terminal.ansiBlack": "#1b1c20",
    "terminal.ansiRed": "#e3655b",
    "terminal.ansiGreen": "#58b287",
    "terminal.ansiYellow": "#d9a03c",
    "terminal.ansiBlue": "#79a3d0",
    "terminal.ansiMagenta": "#b189c9",
    "terminal.ansiCyan": "#6fb2b0",
    "terminal.ansiWhite": "#e9eaec",
    "terminal.ansiBrightBlack": "#5f6268",
    "terminal.ansiBrightRed": "#e3655b",
    "terminal.ansiBrightGreen": "#58b287",
    "terminal.ansiBrightYellow": "#d9a03c",
    "terminal.ansiBrightBlue": "#a9c6e6",
    "terminal.ansiBrightMagenta": "#c9a5db",
    "terminal.ansiBrightCyan": "#8fc7c5",
    "terminal.ansiBrightWhite": "#ffffff",

    "gitDecoration.modifiedResourceForeground": "#79a3d0",
    "gitDecoration.addedResourceForeground": "#58b287",
    "gitDecoration.deletedResourceForeground": "#e3655b",
    "gitDecoration.untrackedResourceForeground": "#58b287",
    "gitDecoration.ignoredResourceForeground": "#5f6268",
    "gitDecoration.conflictingResourceForeground": "#d9a03c",

    "minimap.background": "#101113",
    "minimapSlider.background": "#24262b66",
    "minimapSlider.hoverBackground": "#2e313899",

    "settings.headerForeground": "#e9eaec",
    "settings.modifiedItemIndicator": "#79a3d0",
    "settings.dropdownBackground": "#1b1c20",
    "settings.dropdownBorder": "#ffffff24",
    "settings.textInputBackground": "#1b1c20",
    "settings.numberInputBackground": "#1b1c20",

    "extensionButton.prominentBackground": "#e9eaec",
    "extensionButton.prominentForeground": "#101113",
    "extensionButton.prominentHoverBackground": "#ffffff",
    "extensionBadge.remoteBackground": "#79a3d0",
    "extensionBadge.remoteForeground": "#0f1620"
  },
  "tokenColors": [
    {
      "scope": ["comment", "punctuation.definition.comment"],
      "settings": { "foreground": "#6a6d73", "fontStyle": "italic" }
    },
    {
      "scope": ["string", "punctuation.definition.string"],
      "settings": { "foreground": "#8fc7c5" }
    },
    {
      "scope": ["constant.numeric", "constant.language", "constant.character"],
      "settings": { "foreground": "#d9a03c" }
    },
    {
      "scope": ["keyword", "storage.type", "storage.modifier", "keyword.control"],
      "settings": { "foreground": "#79a3d0" }
    },
    {
      "scope": ["entity.name.function", "support.function", "meta.function-call"],
      "settings": { "foreground": "#a9c6e6" }
    },
    {
      "scope": ["entity.name.type", "entity.name.class", "support.type", "support.class"],
      "settings": { "foreground": "#58b287" }
    },
    {
      "scope": ["variable", "meta.definition.variable.name", "support.variable"],
      "settings": { "foreground": "#e9eaec" }
    },
    {
      "scope": ["variable.parameter"],
      "settings": { "foreground": "#c7c9cd" }
    },
    {
      "scope": ["entity.other.attribute-name", "entity.name.tag"],
      "settings": { "foreground": "#c9a5db" }
    },
    {
      "scope": ["invalid", "invalid.illegal"],
      "settings": { "foreground": "#e3655b" }
    },
    {
      "scope": ["markup.heading", "markup.bold"],
      "settings": { "foreground": "#e9eaec", "fontStyle": "bold" }
    }
  ]
} as const;
